version: '3.8'

services:
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./db/.env
    volumes:
      - type: volume
        source: mysql_test_volume
        target: /var/lib/db
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d
    networks:
      - backend

  smtp:
    container_name: smtp
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - backend

  api:
    container_name: api
    command: >
      /bin/sh -c "dockerize -wait tcp://db:3306 -timeout 60s && air -c .air.toml"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
      - smtp
    volumes:
      - type: bind
        source: ./
        target: /api/src
    networks:
      - backend

volumes:
  mysql_test_volume:
    name: mysql_test_volume

networks:
  backend:
    driver: bridge
