version: '3.8'

services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /go/src
