version: '3.8'

services:
  db_test:
    container_name: db_test
    build:
      context: ./db
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3307:3306
    env_file:
      - .env.test
    volumes:
      - type: volume
        source: mysql_volume_test
        target: /var/lib/db
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d
    networks:
      - backend_test

  smtp_test:
    container_name: smtp_test
    image: mailhog/mailhog
    ports:
      - "8026:8025"
    networks:
      - backend_test

  api_test:
    container_name: api_test
    command: >
      /bin/sh -c "dockerize -wait tcp://db_test:3306 -timeout 90s && air -c .air.toml"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8081:8081
    env_file:
      - .env.test
    depends_on:
      - db_test
      - smtp_test
    volumes:
      - type: bind
        source: ./
        target: /api/src
    networks:
      - backend_test

volumes:
  mysql_volume_test:
    name: mysql_volume_test

networks:
  backend_test:
    driver: bridge
